name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Setup
        run: |
          haxe -version
          haxelib install hx3compat
      - name: Build
        run: |
          make

